// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oycdsiipsryeqhihrzgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95Y2RzaWlwc3J5ZXFoaWhyemdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxNzE2NDAsImV4cCI6MjA4OTc0NzY0MH0.gZyNAaSbXDy48-QzniP4DsOEKrjywNd7RL8cRsxervY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);